query PersonList($search: String $followedBy: String $followerOf: String $likeFor: String $rsvpFor: String $orderBy: String = "-date_joined" $first: Int = 25 $after: String) {
    allPeople(search: $search followedBy: $followedBy followerOf: $followerOf likeFor: $likeFor rsvpFor: $rsvpFor orderBy: $orderBy first: $first after: $after) {
	edges {
  	    node {
		id
		username
		firstName
		lastName
		fullName: name
		shortName
		isBot
		ibisuserPtr {
		    id
		}
  	    }
	    cursor
	}
	pageInfo {
	    hasNextPage
	}
    }
}
