query Nonprofit($id: ID! $self: String){
    nonprofit(id: $id){
	id
	name
	username
	followerCount
	description
	link
	avatar
	banner
	fundraised
	donationFromCount
	newsCount
	eventCount
	ibisuserPtr {
	    id
	}
	isFollowing: follower(id: $self) {
	    edges {
		node {
		    id
		}
	    }
	}
    }
}
