mutation NonprofitSettingsUpdate($id: ID! $username: String $visibilityDonation: String $visibilityTransaction: String) {
    updateNonprofit(id: $id username: $username visibilityDonation: $visibilityDonation visibilityTransaction: $visibilityTransaction) {
	nonprofit {
	    id
	}
    }
}
