mutation NotifierUpdate($id: ID! $emailFollow: Boolean $emailDonation: Boolean $emailTransaction: Boolean $emailComment: Boolean $emailDeposit: Boolean) {
    updateNotifier(id: $id emailFollow: $emailFollow emailDonation: $emailDonation emailTransaction: $emailTransaction emailComment: $emailComment emailDeposit: $emailDeposit) {
	notifier {
	    id
	}
    }
}
