mutation NotifierSettingsUpdate($id: ID! $emailFollow: Boolean $emailTransaction: Boolean $emailComment: Boolean $emailDeposit: Boolean) {
    updateNotifier(id: $id emailFollow: $emailFollow emailTransaction: $emailTransaction emailComment: $emailComment emailDeposit: $emailDeposit) {
	notifier {
	    id
	}
    }
}
