mutation PersonSettingsUpdate($id: ID! $visibilityDonation: String $visibilityTransaction: String) {
    updatePerson(id: $id visibilityDonation: $visibilityDonation visibilityTransaction: $visibilityTransaction) {
	person {
	    id
	}
    }
}
