query Person($id: ID! $self: String){
    person(id: $id) {
	id
	name
	username
	avatar
	donated
	dateJoined
	followerCount
	followingCount
	isFollowing: follower(id: $self) {
	    edges {
		node {
		    id
		}
	    }
	}
    }
}
