query Settings($id: ID!) {
    ibisUser(id: $id) {
	username
	email
	visibilityDonation
	visibilityTransaction
	notifier {
	    id
	    emailFollow
	    emailDonation
	    emailTransaction
	    emailComment
	    emailDeposit
	}
    }
}
