query Settings($id: ID!) {
    person(id: $id) {
	username
	visibilityDonation
	visibilityTransaction
	notifier {
	    id
	    emailFollow
	    emailTransaction
	    emailComment
	    emailLike
	}
    }
}
