query ActivityList($self: String $search: String $user: String $byFollowing: String $bookmarkBy: String $orderBy: String $first: Int! $after: String) {
    allActivities(search: $search user: $user byFollowing: $byFollowing bookmarkBy: $bookmarkBy orderBy: $orderBy first: $first after: $after) {
	edges {
  	    node {
		id
		title
		created
		description
		likeCount
		active
		rewardMin
		rewardRange
		user {
		    id
		    name
		    username
		    avatar
		}
		hasLiked: like(id: $self) {
		    edges {
			node {
			    id
			}
		    }
		}
		hasBookmarked: bookmark(id: $self) {
		    edges {
			node {
			    id
			}
		    }
		}
	    }
	    cursor
	}
	pageInfo {
	    hasNextPage
	}
    }
}
