mutation ChallengeUpdate($id: ID! $user: ID $title: String $description: String $active: Boolean $rewardMin: Int $rewardRange: Int) {
    updateChallenge(id: $id user: $user title: $title description: $description active: $active rewardMin: $rewardMin rewardRange: $rewardRange) {
	challenge {
	    id
	}
    }
}
