mutation CommentCreate($user: ID! $parent: ID! $description: String! $self: String! $mention: [ID]) {
    createComment(user: $user parent: $parent description: $description mention: $mention) {
	comment {
	    id
	    description
	    created
	    user {
		id
		name
		username
		avatar
		person {
		    id
		}
		nonprofit {
		    id
		}
	    }
	    hasLiked: like(id: $self) {
		edges {
		    node {
			id
		    }
		}
	    }
	    entryPtr {
		id
		commentCount
	    }
	}
    }
}
