query CommentList($parent: String! $self: String) {
    allComments(parent: $parent orderBy: "-created") {
	edges {
	    node {
		id
		description
		created
		likeCount
		mention {
		    edges {
			node {
			    id
			    username
			    userType
			}
		    }
		}
		user {
		    id
		    name
		    username
		    avatar
		    userType
		}
		hasLiked: like(id: $self) {
		    edges {
			node {
			    id
			}
		    }
		}
		parent {
		    id
		    comment {
			id
			user {
			    id
			    username
			}
		    }
		}
	    }
	}
    }
}
