query Donation($id: ID! $self: String){
    donation(id: $id) {
	id
	amount
	description 
	private
	created
	likeCount
	mention {
	    edges {
		node {
		    id
		    username
		    organization {
			id
		    }
		    person {
			id
		    }
		}
	    }
	}
	user {
	    id
	    username
	    name
	    avatar
	    person {
		id
	    }
	    organization {
		id
	    }
	}
	target {
	    id
	    username
	    name
	    category {
		id
	    }
	}
	hasLiked: like(id: $self) {
	    edges {
		node {
		    id
		}
	    }
	}
	hasBookmarked: bookmark(id: $self) {
	    edges {
		node {
		    id
		}
	    }
	}
    }
}
