query DonationForm($id: ID! $target: ID!) {
    user: ibisUser(id: $id) {
	id
	balance
    }
    target: nonprofit(id: $target) {
	id
	name
	username
    }
    message: allDonationMessages(nonprofit: $target random: true first: 1) {
	edges {
	    node {
		id
		description
	    }
	}
    }
}
