query DonationList($self: String $search: String $withUser: String $withFollowing: String $includeInvestment: Boolean = false $withInvestment: String $bookmarkBy: String $orderBy: String $first: Int! $after: String) {
    allDonations(search: $search withUser: $withUser withFollowing: $withFollowing withInvestment: $withInvestment bookmarkBy: $bookmarkBy orderBy: $orderBy first: $first after: $after) {
	edges {
  	    node {
		id
		amount
		description
		private
		created
		likeCount
		user {
		    id
		    name
		    avatar
		}
		target {
		    id
		    name
		    category {
			id
		    }
		}
		hasLiked: like(id: $self) {
		    edges {
			node {
			    id
			}
		    }
		}
		hasBookmarked: bookmark(id: $self) {
		    edges {
			node {
			    id
			}
		    }
		}
		commenterRecursive {
		    edges {
			node {
			    id
			    avatar
			}
		    }
		}
		investmentAmount(withInvestment: $withInvestment) @include(if: $includeInvestment) {
		    edges {
			node {
			    id
			    amount
			}
		    }
		}
	    }
	    cursor
	}
	pageInfo {
	    hasNextPage
	}
    }
}
