query Donation($id: ID! $self: String){
    donation(id: $id) {
	id
	amount
	description 
	created
	likeCount
	mention {
	    edges {
		node {
		    id
		    username
		    userType
		}
	    }
	}
	user {
	    id
	    username
	    name
	    avatar
	}
	target {
	    id
	    username
	    name
	}
	hasLiked: like(id: $self) {
	    edges {
		node {
		    id
		}
	    }
	}
	hasBookmarked: bookmark(id: $self) {
	    edges {
		node {
		    id
		}
	    }
	}
    }
}
