mutation EventUpdate($id: ID! $user: ID $title: String $image: Upload $description: String $link: String $date: String $duration: Int $address: String $virtual: Boolean) {
    updateEvent(id: $id user: $user title: $title image: $image description: $description link: $link date: $date duration: $duration address: $address virtual: $virtual) {
	event {
	    id
	}
    }
}
