query EventList($self: String $search: String $user: String $byFollowing: String $bookmarkBy: String $rsvpBy: String $beginDate: String $orderBy: String $first: Int! $after: String) {
    allEvents(search: $search user: $user byFollowing: $byFollowing bookmarkBy: $bookmarkBy rsvpBy: $rsvpBy beginDate: $beginDate orderBy: $orderBy first: $first after: $after) {
	edges {
  	    node {
		id
  		title
		image
  		description
  		created
		date
		likeCount
		rsvpCount
		user {
		    id
		    name
		    username
		    avatar
		    category {
			id
		    }
		}
		hasLiked: like(id: $self) {
		    edges {
			node {
			    id
			}
		    }
		}
		hasBookmarked: bookmark(id: $self) {
		    edges {
			node {
			    id
			}
		    }
		}
		hasRsvp: rsvp(id: $self) {
		    edges {
			node {
			    id
			}
		    }
		}
	    }
	    cursor
	}
	pageInfo {
	    hasNextPage
	}
    }
}
