query Event($id: ID! $self: String){
    event(id: $id){
	id
	title
	image
	created
	modified
	description
	date
	duration
	address
	virtual
	link
	likeCount
	rsvpCount
	mention {
	    edges {
		node {
		    id
		    username
		    userType
		}
	    }
	}
	user {
	    id
	    name
	    username
	    avatar
	}
	hasLiked: like(id: $self) {
	    edges {
		node {
		    id
		}
	    }
	}
	hasBookmarked: bookmark(id: $self) {
	    edges {
		node {
		    id
		}
	    }
	}
	hasRsvp: rsvp(id: $self) {
	    edges {
		node {
		    id
		}
	    }
	}
    }
}
