mutation EventUpdate($id: ID! $user: ID $title: String $image: String $description: String $link: String $date: String $duration: Int $address: String) {
    updateEvent(id: $id user: $user title: $title image: $image description: $description link: $link date: $date duration: $duration address: $address) {
	event {
	    id
	}
    }
}
