query GrantList($user: String $orderBy: String = "-created" $first: Int! $after: String) {
    allGrants(user: $user orderBy: $orderBy first: $first after: $after) {
	edges {
  	    node {
		id
		name
		amount
		duration
		created
		description
		numDonations
		numOrganizations
		fundedAmount
		user {
		    id
		}
	    }
	    cursor
	}
	pageInfo {
	    hasNextPage
	}
    }
}
