query MessageList($withUser: String! $orderBy: String = "-created" $first: Int = 25 $after: String) {
    allMessages(withUser: $withUser orderBy: $orderBy first: $first after: $after) {
	edges {
  	    node {
		id
		description
		created
		user {
		    id
		}
		target {
		    id
		}
	    }
	    cursor
	}
	pageInfo {
	    hasNextPage
	}
    }
}
