query News($id: ID! $self: String){
    news(id: $id){
	id
	title
	created
	modified
	description
	image
	likeCount
	link
	mention {
	    edges {
		node {
		    id
		    username
		    userType
		}
	    }
	}
	user {
	    id
	    name
	    username
	    avatar
	    category {
		id
	    }
	}
	hasLiked: like(id: $self) {
	    edges {
		node {
		    id
		}
	    }
	}
	hasBookmarked: bookmark(id: $self) {
	    edges {
		node {
		    id
		}
	    }
	}
    }
}
