mutation NonprofitUpdate($id: ID! $username: String $description: String $privacyDonation: Boolean $privacyTransaction: Boolean $privacyDeposit: Boolean $avatar: Upload $banner: Upload) {
    updateNonprofit(id: $id username: $username description: $description privacyDonation: $privacyDonation privacyTransaction: $privacyTransaction privacyDeposit: $privacyDeposit avatar: $avatar banner: $banner) {
	nonprofit {
	    id
	}
    }
}
