mutation NonprofitUpdate($id: ID! $username: String $description: String $email: String $visibilityDonation: String $visibilityTransaction: String $avatar: Upload $banner: Upload) {
    updateNonprofit(id: $id username: $username description: $description email: $email visibilityDonation: $visibilityDonation visibilityTransaction: $visibilityTransaction avatar: $avatar banner: $banner) {
	nonprofit {
	    id
	}
    }
}
