mutation NonprofitUpdate($id: ID! $username: String $description: String $email: String $visibilityDonation: String $visibilityTransaction: String) {
    updateNonprofit(id: $id username: $username description: $description email: $email visibilityDonation: $visibilityDonation visibilityTransaction: $visibilityTransaction) {
	nonprofit {
	    id
	}
    }
}
