mutation NotifierUpdate($id: ID! $emailDonation: Boolean $emailReward: Boolean $emailComment: Boolean $emailMention: Boolean $emailDeposit: Boolean $emailWithdrawal: Boolean $emailGrant: Boolean $emailMessage: Boolean) {
    updateNotifier(id: $id emailDonation: $emailDonation emailReward: $emailReward emailComment: $emailComment emailMention: $emailMention emailDeposit: $emailDeposit emailWithdrawal: $emailWithdrawal emailGrant: $emailGrant emailMessage: $emailMessage) {
	notifier {
	    id
	}
    }
}
