query Organization($id: ID! $self: String){
    organization(id: $id){
	id
	name
	username
	followingCount
	followerCount
	description
	link
	avatar
	banner
	isActive
	fundraised
	newsCount
	eventCount
	donationReceivedCount
	recentResponseRate
	isFollowing: follower(id: $self) {
	    edges {
		node {
		    id
		}
	    }
	}
    }
}
