mutation OrganizationUpdate($id: ID! $username: String $description: String $avatar: Upload $banner: Upload) {
    updateOrganization(id: $id username: $username description: $description avatar: $avatar banner: $banner) {
	organization {
	    id
	}
    }
}
