mutation PersonUpdate($id: ID! $username: String $description: String $privacyDonation: Boolean $privacyTransaction: Boolean $privacyDeposit: Boolean $avatar: Upload) {
    updatePerson(id: $id username: $username description: $description privacyDonation: $privacyDonation privacyTransaction: $privacyTransaction privacyDeposit: $privacyDeposit avatar: $avatar) {
	person {
	    id
	}
    }
}
