mutation PersonUpdate($id: ID! $username: String $description: String $avatar: Upload) {
    updatePerson(id: $id username: $username description: $description avatar: $avatar) {
	person {
	    id
	}
    }
}
