query Person($id: ID! $self: String){
    person(id: $id) {
	id
	name
	username
	avatar
	description
	donated
	dateJoined
	followerCount
	followingCount
	donationWithCount
	transactionWithCount
	postCount
	eventRsvpCount
	ibisuserPtr {
	    id
	}
	isFollowing: follower(id: $self) {
	    edges {
		node {
		    id
		}
	    }
	}
    }
}
