mutation PersonUpdate($id: ID! $username: String $description: String $visibilityDonation: String $visibilityTransaction: String) {
    updatePerson(id: $id username: $username description: $description visibilityDonation: $visibilityDonation visibilityTransaction: $visibilityTransaction) {
	person {
	    id
	}
    }
}
