mutation PostCreate($user: ID! $title: String! $description: String! $mention: [ID]) {
    createPost(user: $user title: $title description: $description mention: $mention) {
	post {
	    id
	}
    }
}
