query RewardList($self: String $search: String $withUser: String $withFollowing: String $bookmarkBy: String $orderBy: String $first: Int! $after: String) {
    allRewards(search: $search withUser: $withUser withFollowing: $withFollowing bookmarkBy: $bookmarkBy orderBy: $orderBy first: $first after: $after) {
	edges {
  	    node {
		id
		amount
		description
		private
		created
		likeCount
		target {
		    id
		    name
		}
		user {
		    id
		    name
		    avatar
		    person {
			id
		    }
		    organization {
			id
		    }
		}
		hasLiked: like(id: $self) {
		    edges {
			node {
			    id
			}
		    }
		}
		hasBookmarked: bookmark(id: $self) {
		    edges {
			node {
			    id
			}
		    }
		}
	    }
	    cursor
	}
	pageInfo {
	    hasNextPage
	}
    }
}
