query Settings($id: ID!) {
    user(id: $id) {
	firstName
	username
	description
	email
	notifier {
	    id
	    emailDonation
	    emailReward
	    emailComment
	    emailMention
	    emailGrant
	    emailWithdrawal
	    emailMessage
	    emailGrant
	}
	person {
	    id
	    verified
	    phoneNumber
	}
    }
}
