query Settings($id: ID!) {
    user(id: $id) {
	firstName
	username
	description
	email
	notifier {
	    id
	    emailFollow
	    emailDonation
	    emailReward
	    emailComment
	    emailMention
	    emailDeposit
	}
	person {
	    id
	    verified
	    phoneNumber
	}
    }
}
