query Settings($id: ID!) {
    ibisUser(id: $id) {
	username
	description
	email
	privacyDonation
	privacyTransaction
	privacyDeposit
	notifier {
	    id
	    emailFollow
	    emailDonation
	    emailTransaction
	    emailComment
	    emailMention
	    emailDeposit
	}
    }
}
