query WithdrawalList($user: String $orderBy: String $first: Int! $after: String) {
    allWithdrawals(user: $user orderBy: $orderBy first: $first after: $after) {
	edges {
  	    node {
		id
		amount
		created
		description
	    }
	    cursor
	}
	pageInfo {
	    hasNextPage
	}
    }
}
