query ActivityList($search: String $user: String $scratch: String $active: Boolean $createdAfter: String  $createdBefore: String $orderBy: String = "-active,-created" $first: Int = 25 $after: String) {
    allActivities(search: $search user: $user scratch: $scratch active: $active createdAfter: $createdAfter createdBefore: $createdBefore orderBy: $orderBy first: $first after: $after) {
	edges {
  	    node {
		id
		title
		description
		created
		likeCount
		active
		rewardMin
		rewardRange
		scratch
		user {
		    id
		    username
		    name
		    firstName
		}
	    }
	    cursor
	}
	pageInfo {
	    hasNextPage
	}
    }
}
