query ActivityList($search: String $user: String $byFollowing: String $bookmarkBy: String $scratch: String $orderBy: String $first: Int! $after: String) {
    allActivities(search: $search user: $user byFollowing: $byFollowing bookmarkBy: $bookmarkBy scratch: $scratch orderBy: $orderBy first: $first after: $after) {
	edges {
  	    node {
		id
		title
		description
		created
		likeCount
		active
		rewardMin
		rewardRange
		scratch
		user {
		    id
		    username
		    name
		    firstName
		}
	    }
	    cursor
	}
	pageInfo {
	    hasNextPage
	}
    }
}
