query ActivityNode($id: ID!){
    activity(id: $id){
	id
	title
	description
	created
	likeCount
	active
	rewardMin
	rewardRange
	scratch
	user {
	    id
	    username
	    name
	    firstName
	}
    }
}
