mutation BotUpdate($id: ID! $description: String $scratch: String) {
    updateBot(id: $id description: $description scratch: $scratch) {
	bot {
	    id
	    username
	    name
	    scratch
	}
    }
}
