mutation BotUpdate($id: ID! $description: String $privacyDonation: Boolean $privacyTransaction: Boolean) {
    updateBot(id: $id description: $description privacyDonation: $privacyDonation privacyTransaction: $privacyTransaction) {
	bot {
	    id
	}
    }
}
