query ChallengeList($self: String $search: String $byUser: String $byFollowing: String $bookmarkBy: String $orderBy: String $first: Int! $after: String) {
    allChallenges(search: $search byUser: $byUser byFollowing: $byFollowing bookmarkBy: $bookmarkBy orderBy: $orderBy first: $first after: $after) {
	edges {
  	    node {
		title
		description
		created
		likeCount
		active
		rewardMin
		rewardRange
		user {
		    id
		}
	    }
	    cursor
	}
	pageInfo {
	    hasNextPage
	}
    }
}
