mutation ChallengeCreate($user: ID! $title: String! $description: String! $active: Boolean $rewardMin: Int $rewardRange: Int) {
    createChallenge(user: $user title: $title description: $description active: $active rewardMin: $rewardMin rewardRange: $rewardRange) {
	challenge {
	    id
	}
    }
}
