query CommentNode($id: ID!) {
    comment(id: $id) {
	id
	description
	created
	likeCount
	user {
	    id
	    userType
	    username
	    name
	    firstName
	}
	mention {
	    edges {
		node {
		    id
		    userType
		    username
		    name
		    firstName
		}
	    }
	}
    }
}
