query CommentList($parent: String! $orderBy: String = "-created" $first: Int = 25 $after: String) {
    allComments(parent: $parent orderBy: $orderBy first: $first after: $after) {
	edges {
	    node {
		id
		description
		created
		likeCount
		entryType
		user {
		    id
		    userType
		}
	    }
	}
    }
}
