mutation CommentCreate($user: ID! $parent: ID! $description: String! $scratch: String) {
    createComment(user: $user parent: $parent description: $description scratch: $scratch) {
	comment {
	    id
	    description
	    created
	    likeCount
	    user {
		id
		userType
		username
		name
		firstName
	    }
	    mention {
		edges {
		    node {
			id
			username
			userType
		    }
		}
	    }
	}
    }
}
