query CommentList($hasParent: String! $orderBy: String = "-created" $first: Int = 25 $after: String) {
    allComments(hasParent: $hasParent orderBy: $orderBy first: $first after: $after) {
	edges {
	    node {
		id
		description
		created
		likeCount
		user {
		    id
		    bot {
			id
		    }
		    organization {
			id
		    }
		}
		entryPtr {
		    id
		}
		parent {
		    id
		    donation {
			id
		    }
		    reward {
			id
		    }
		    news { 
			id
		    }
		    event {
			id
		    }
		    post {
			id
		    }
		    comment {
			id
		    }
		}
	    }
	}
    }
}
