mutation CommentCreate($user: ID! $parent: ID! $description: String! $scratch: String) {
    createComment(user: $user parent: $parent description: $description scratch: $scratch) {
	comment {
	    id
	}
    }
}
