query DonationNode($id: ID!) {
    donation(id: $id) {
	id
	amount
	description
	created
	likeCount
	user {
	    id
	    username
	    name
	    firstName
	}
	target {
	    id
	    username
	    name
	    firstName
	}
    }
}
