query DonationList($search: String $user: String $withGrant: String $createdAfter: String  $createdBefore: String $orderBy: String = "-created" $first: Int = 25 $after: String) {
    allDonations(search: $search user: $user withGrant: $withGrant createdAfter: $createdAfter createdBefore: $createdBefore orderBy: $orderBy first: $first after: $after) {
	edges {
  	    node {
		id
		amount
		description
		created
		likeCount
		user {
		    id
		    username
		    name
		    firstName
		}
		target {
		    id
		    username
		    name
		    firstName
		}
	    }
	    cursor
	}
	pageInfo {
	    hasNextPage
	}
    }
}
