query EventList($search: String $user: String $rsvpBy: String $createdAfter: String  $createdBefore: String $orderBy: String = "-created" $first: Int = 25 $after: String) {
    allEvents(search: $search user: $user rsvpBy: $rsvpBy createdAfter: $createdAfter createdBefore: $createdBefore orderBy: $orderBy first: $first after: $after) {
	edges {
  	    node {
		id
		title
		description
		created
		likeCount
		date
		duration
		address
		user {
		    id
		    username
		    name
		    firstName
		}
	    }
	    cursor
	}
	pageInfo {
	    hasNextPage
	}
    }
}
