query NotificationList($user: String $clicked: Boolean $orderBy: String = "-created" $first: Int! $after: String) {
    allNotifications(user: $user clicked: $clicked orderBy: $orderBy first: $first after: $after) {
	edges {
	    node {
		id
		category
		clicked
		reference
		created
	    }
	    cursor
	}
	pageInfo {
	    hasNextPage
	}
    }
}
