mutation PersonUpdate($id: ID! $description: String $privacyDonation: Boolean $privacyTransaction: Boolean) {
    updatePerson(id: $id description: $description privacyDonation: $privacyDonation privacyTransaction: $privacyTransaction) {
	person {
	    id
	}
    }
}
