mutation RewardCreate($user: ID! $target: ID! $amount: Int! $description: String! $scratch: String) {
    createReward(user: $user target: $target amount: $amount description: $description scratch: $scratch) {
	reward {
	    id
	}
    }
}
