query Reward($id: ID!) {
    reward(id: $id) {
	id
	amount
	description
	created
	likeCount
	target {
	    id
	    bot {
		id
	    }
	}
	user {
	    id
	    organization {
		id
	    }
	    bot {
		id
	    }
	}
    }
}
