query RewardNode($id: ID!) {
    reward(id: $id) {
	id
	amount
	description
	created
	likeCount
	scratch
	user {
	    id
	    username
	    name
	    firstName
	}
	target {
	    id
	    username
	    name
	    firstName
	}
    }
}
