query RewardList($search: String $user: String $scratch: String $orderBy: String = "-created" $first: Int = 25 $after: String) {
    allRewards(search: $search user: $user scratch: $scratch orderBy: $orderBy first: $first after: $after) {
	edges {
  	    node {
		id
		amount
		description
		created
		likeCount
		scratch
		user {
		    id
		    username
		    name
		    firstName
		}
		target {
		    id
		    username
		    name
		    firstName
		}
	    }
	    cursor
	}
	pageInfo {
	    hasNextPage
	}
    }
}
