query TransactionList($search: String $byUser: String $orderBy: String = "-created" $first: Int = 25 $after: String) {
    allTransactions(search: $search byUser: $byUser orderBy: $orderBy first: $first after: $after) {
	edges {
  	    node {
		id
		amount
		description
		created
		likeCount
		target {
		    id
		}
		user {
		    id
		    organization {
			id
		    }
		    person {
			id
			bot {
			    id
			}
		    }
		}
	    }
	    cursor
	}
	pageInfo {
	    hasNextPage
	}
    }
}
