query Transaction($id: ID!) {
    transaction(id: $id) {
	id
	amount
	description
	created
	likeCount
	target {
	    id
	    bot {
		id
	    }
	}
	user {
	    id
	    nonprofit {
		id
	    }
	    person {
		id
		bot {
		    id
		}
	    }
	}
    }
}
